"""Knowledge base — humanities, lifestyle, travel, sports & design topics."""

KB_LIFE = {
    "History of Nepal": {
        "terms": {
            "Lichchhavi period": "the era from roughly 400 to 750 CE, the earliest well-documented age of the Kathmandu Valley, known from stone inscriptions",
            "Malla dynasty": "the valley rulers whose reign is remembered as a golden age of art, architecture and trade before unification",
            "Unification era": "the campaign in which Prithvi Narayan Shah of Gorkha conquered the valley in 1768-69 and forged modern Nepal",
            "Bhimsen Thapa": "Nepal's first prime minister, who led the country during the Anglo-Nepalese War of 1814-16",
            "Treaty of Sugauli": "the 1816 agreement that ended war with the East India Company and redrew Nepal's western border",
            "Rana rule": "the hereditary prime-ministerial regime from 1846 to 1951 that kept kings as figureheads",
        },
        "facts": [
            "Prithvi Narayan Shah captured Kathmandu in 1768 by attacking during Indra Jatra celebrations.",
            "After Yaksha Malla's death the valley split into the three rival kingdoms of Kathmandu, Patan and Bhaktapur.",
            "The Treaty of Sugauli ceded roughly a third of pre-war Nepali territory to British India.",
            "The 1951 revolution ended Rana rule and restored royal authority.",
        ],
    },
    "Nepali Culture & Festivals": {
        "terms": {
            "Newari traditions": "the indigenous culture of the Kathmandu Valley with its own language, cuisine, festivals and guild societies",
            "Folk stories": "oral tales of spirits, kings and clever animals passed down generations across Nepal",
            "Major festivals": "celebrations like Dashain and Tihar that structure the Nepali ritual calendar",
            "Dashain": "the fifteen-day autumn festival when elders bless family members with rice tika and blessings",
            "Tihar": "the five-day festival of lights honoring crows, dogs, cows and finally siblings through Bhai Tika",
            "Guthi": "traditional Newari trusts that maintain temples and organize community feasts and rituals",
        },
        "facts": [
            "During Dashain, receiving tika from elders reaffirms family bonds across generations.",
            "On Kukur Tihar people garland and feed dogs to honor their loyalty.",
            "Newari feasts called bhoj are seated by custom, with courses served in strict order.",
            "Many Nepali festivals follow the lunar calendar, so their Gregorian dates shift each year.",
        ],
    },
    "Nepali Literature": {
        "terms": {
            "Laxmi Prasad Devkota": "Nepal's national poet, a prolific modernizer of Nepali verse and drama",
            "Muna Madan": "Devkota's folk epic about a trader who leaves his wife for the Lhasa road, written in popular jhyaure meter",
            "Parijat": "the pen name of Bishnu Kumari Waiba, one of Nepal's most influential novelists",
            "Shirishko Phool": "Parijat's novel The Blue Mimosa, the first book by a woman to win the Madan Puraskar in 1965",
            "Madan Puraskar": "Nepal's most prestigious literary award, given annually since 1956",
            "Jhyaure meter": "a folk song rhythm Devkota famously adapted for epic poetry",
        },
        "facts": [
            "Muna Madan contains Devkota's famous line that greatness lies in the heart, not in caste or wealth.",
            "Devkota wrote Muna Madan while bedridden, reportedly composing it faster than scribes could take dictation.",
            "Shirishko Phool explores trauma and alienation through characters scarred by war.",
            "Devkota also translated his own work into English, bridging Nepali letters to wider readers.",
        ],
    },
    "Modern English Fiction": {
        "terms": {
            "George Orwell": "the pen name of Eric Arthur Blair, essayist and novelist of totalitarian warning tales",
            "Dystopian fiction": "stories imagining oppressive future societies to critique present-day tendencies",
            "Post-colonialism": "the literary field examining how colonialism and its aftermath shape texts and identities",
            "Allegory": "narrative in which characters and events stand for broader political or moral meanings",
            "Unreliable narrator": "a storyteller whose credibility is compromised, forcing readers to read between lines",
        },
        "facts": [
            "Animal Farm retells the Soviet revolution as farmyard allegory, with pigs becoming the new masters.",
            "The novel 1984 introduced terms like Big Brother, doublethink and thoughtcrime into everyday speech.",
            "Chinua Achebe's Things Fall Apart answered colonial caricature with an Igbo-centered narrative.",
            "Orwell argued in Politics and the English Language that vague prose enables political deceit.",
        ],
    },
    "World Mythology": {
        "terms": {
            "Archetypes": "recurring universal figures such as the hero, trickster and mentor found across cultures",
            "Monomyth": "Joseph Campbell's hero's journey: departure, initiation and return",
            "Oral traditions": "myth transmission by speech alone, preserving epics long before they were written down",
            "Deity pantheons": "families of gods such as the Greek Olympians or Norse Aesir with distinct domains",
            "Creation myth": "a culture's account of how the world began, often explaining order out of chaos",
            "Trickster figure": "a boundary-crossing deity like Loki or Anansi who disrupts rules yet drives change",
        },
        "facts": [
            "Campbell's monomyth underlies narratives from Homer's Odyssey to modern film trilogies.",
            "Homer's epics survived centuries of oral performance before being written down.",
            "Trickster myths often explain how disorder paradoxically renews the world.",
            "Comparing creation myths reveals shared themes like flood, egg and cosmic order.",
        ],
    },
    "Philosophy": {
        "terms": {
            "Dualism": "the view that mind and body are fundamentally different kinds of substance, associated with Descartes",
            "Empiricism": "the doctrine that knowledge derives primarily from sensory experience, championed by Locke and Hume",
            "Rationalism": "the doctrine that reason rather than sense experience is the chief source of knowledge",
            "Consciousness": "subjective experience itself; its 'hard problem' asks why physical processes feel like anything at all",
            "Epistemology": "the branch of philosophy studying knowledge, justification and belief",
            "Ethics": "the systematic study of right action, duty and the good life",
        },
        "facts": [
            "Descartes' methodological doubt led him to the one certainty he could not doubt: that doubting was occurring.",
            "Hume argued induction cannot be rationally justified, challenging science's logical foundations.",
            "Kant attempted to synthesize rationalism and empiricism through transcendental idealism.",
            "Thought experiments like the trolley problem probe moral intuitions systematically.",
        ],
    },
    "Political Philosophy": {
        "terms": {
            "Social contract": "the idea that legitimate authority rests on the consent of the governed, developed by Hobbes, Locke and Rousseau",
            "Separation of powers": "dividing legislative, executive and judicial functions so no branch dominates, articulated by Montesquieu",
            "Totalitarianism": "rule seeking total control over public and private life through ideology and terror",
            "Liberalism": "tradition prioritizing individual rights, consent and limited government",
            "Utilitarianism": "evaluating actions by their consequences for total welfare, associated with Bentham and Mill",
            "Civil disobedience": "public, conscientious lawbreaking meant to expose injustice, defended by Thoreau and King",
        },
        "facts": [
            "Hobbes justified absolute sovereignty as escape from the state of nature's war of all against all.",
            "Locke's natural rights of life, liberty and property shaped later democratic constitutions.",
            "Montesquieu's Spirit of the Laws directly influenced the framers of the US Constitution.",
            "Mill defended liberty except where harm to others provides grounds for interference.",
        ],
    },
    "Current Affairs & Politics": {
        "terms": {
            "Election coverage": "reporting on campaigns, polling, results and the integrity of electoral processes",
            "Policy explainers": "journalism translating legislative and regulatory mechanics into everyday impact",
            "Geopolitics": "analysis of how geography, resources and borders shape relations between states",
            "Federalism": "constitutional division of power between national and provincial governments",
            "Sanctions": "economic penalties designed to change another state's behavior without open conflict",
            "Coalition politics": "governance built from alliances among parties when no single party holds a majority",
        },
        "facts": [
            "Pre-election polls measure snapshots, not certainties, and margins carry sampling error.",
            "Sanctions often impose the heaviest costs on civilians rather than targeted elites.",
            "Coalition governments trade stability for broader representation.",
            "Reading primary sources, not only summaries, guards against distorted coverage.",
        ],
    },
    "International Law": {
        "terms": {
            "Sovereignty": "the supreme authority of states within their own borders, the cornerstone of the Westphalian order",
            "Treaty ratification": "the formal act by which a state consents to be bound by a treaty it has signed",
            "Humanitarian law": "the Geneva Conventions regime limiting wartime conduct and protecting civilians and prisoners",
            "Vienna Convention": "the 1969 framework treaty governing how treaties are made, interpreted and ended",
            "Extradition": "the surrender of an accused person between states under treaty obligations",
            "Diplomatic immunity": "protection shielding accredited diplomats from local prosecution under the 1961 Vienna Convention",
        },
        "facts": [
            "Signing a treaty signals intent, but only ratification generally binds a state under international law.",
            "The four Geneva Conventions of 1949 are among the most widely ratified treaties in the world.",
            "Sovereign equality means no state legally outranks another despite power differences.",
            "Customary international law binds even states that never signed specific treaties.",
        ],
    },
    "Psychology & Human Behavior": {
        "terms": {
            "Cognitive bias": "a systematic deviation from rational judgment caused by mental shortcuts",
            "Classical conditioning": "learning by association, in which a neutral stimulus paired with a reflex-producing one elicits the response alone",
            "Habit formation": "automating behavior through repeated cue-routine-reward loops",
            "Confirmation bias": "the tendency to seek and trust information supporting existing beliefs",
            "Operant conditioning": "learning in which consequences shape behavior through reinforcement and punishment",
            "Anchoring effect": "over-relying on the first number presented when estimating value",
        },
        "facts": [
            "Pavlov's dogs salivated at a bell after it repeatedly predicted food.",
            "Habits cue off context, which is why changing environments disrupts unwanted routines.",
            "Confirmation bias makes disconfirming evidence feel weaker than it is.",
            "Rewards delivered unpredictably sustain behavior longer than predictable ones.",
        ],
    },
    "Linguistics": {
        "terms": {
            "Syntax trees": "diagrams representing the hierarchical phrase structure beneath word order",
            "Phonemes": "the smallest sound units distinguishing meaning, about forty-four in English",
            "Morphology": "the study of morphemes, the smallest meaningful pieces such as roots and affixes",
            "Language learning tips": "practices like comprehensible input and spaced retrieval that speed acquisition",
            "Semantics": "the study of meaning in words, phrases and sentences",
            "Pragmatics": "how context shapes what utterances actually communicate beyond literal meaning",
        },
        "facts": [
            "Changing one phoneme can flip meaning, as pin becomes bin.",
            "Un-, cat and -s are separate morphemes inside the word uncats.",
            "Children acquire grammar rapidly without formal instruction, whatever their language.",
            "Politeness strategies differ by culture, which is why literal translation often sounds rude.",
        ],
    },
    "Archeology": {
        "terms": {
            "Stratigraphy": "reading layered deposits, where deeper layers were generally laid down earlier",
            "Radiocarbon dating": "measuring carbon-14 decay to date organic remains back about fifty thousand years",
            "Artifact conservation": "stabilizing excavated objects against decay once their burial environment changes",
            "Excavation context": "recording exactly where and with what each find lay, since provenance carries meaning",
            "Typology": "classifying artifacts by form and style to build relative chronologies",
        },
        "facts": [
            "The law of superposition makes undisturbed lower strata older than those above them.",
            "Radiocarbon dating works only on organic material such as bone, charcoal and shell.",
            "Moving an artifact without recording context destroys most of its scientific value.",
            "Stone tools survive millennia while textiles and wood usually perish, skewing the record.",
        ],
    },
    "Fitness & Strength Training": {
        "terms": {
            "Progressive overload": "gradually increasing weight, reps or difficulty so the body keeps adapting",
            "Home workouts": "bodyweight progressions like push-up and squat variations that build strength without equipment",
            "Gym routines": "structured splits such as push-pull-legs that organize weekly training volume",
            "Compound movements": "multi-joint lifts like squats and deadlifts that train large muscle groups together",
            "Muscle recovery": "rest days plus sleep and protein, during which tissue actually adapts and grows",
            "Warm-up sets": "lighter preparatory sets raising temperature and grooving movement patterns",
        },
        "facts": [
            "Strength gains early in training come mostly from neural adaptation before muscle growth appears.",
            "Training a muscle twice weekly tends to beat once weekly at equal total volume.",
            "Sleep deprivation measurably reduces strength output and recovery rate.",
            "Soreness indicates novelty more than effectiveness; progression matters far more.",
        ],
    },
    "Nutrition & Diet": {
        "terms": {
            "Macros": "protein, carbohydrate and fat — the energy-yielding nutrients supplying roughly four, four and nine calories per gram",
            "Meal prep": "batch-cooking meals ahead so weekday choices stay consistent",
            "Intermittent fasting": "confining eating to time windows, an adherence strategy rather than metabolic magic",
            "Reading food labels": "checking serving size, ingredient order and added sugars before trusting front-of-pack claims",
            "Protein requirements": "roughly zero-point-eight grams per kilogram bodyweight daily, higher for active people",
            "Calorie deficit": "eating below expenditure, the necessary condition of fat loss regardless of diet style",
        },
        "facts": [
            "Ingredients are listed by weight, so sugar leading the list means sugar dominates the product.",
            "Fat supplies nine calories per gram, more than double protein or carbohydrate.",
            "Diets fail mostly through poor adherence, not because of metabolic differences.",
            "Whole foods raise satiety per calorie compared with ultra-processed equivalents.",
        ],
    },
    "Mental Health": {
        "terms": {
            "Anxiety management": "skills like slow breathing, grounding and graded exposure that lower day-to-day symptoms",
            "Therapy basics": "structured talk therapies such as CBT that retrain unhelpful thought patterns",
            "Journaling": "expressive writing that reduces rumination and clarifies emotions",
            "Sleep hygiene": "consistent schedules, dark cool rooms and screen-free wind-downs protecting mental health",
            "Burnout": "chronic workplace stress showing up as exhaustion, cynicism and reduced effectiveness",
            "Grounding techniques": "sensory exercises like five-four-three-two-one that pull attention out of spirals",
        },
        "facts": [
            "Slow exhale-weighted breathing activates the parasympathetic system within minutes.",
            "CBT's core claim is testable: changing thought patterns changes emotional responses.",
            "Sleep disruption both worsens and mimics psychiatric symptoms, making it a first-line fix.",
            "Burnout responds to workload and control changes, not just individual resilience tips.",
        ],
    },
    "Cooking & Recipes": {
        "terms": {
            "Nepali cuisine": "centered on dal-bhat with lentils, rice, seasonal vegetables and pickles like achar",
            "Quick weeknight meals": "one-pot dishes and high-heat stir-fries that cut cooking and cleaning time",
            "Baking basics": "weighed ingredients and accurate oven temperatures, since baking ratios tolerate little drift",
            "Knife skills": "claw grip and consistent cuts that cook evenly and keep fingers safe",
            "Maillard reaction": "browning between proteins and sugars above roughly 140 degrees C that creates deep flavor",
            "Mise en place": "preparing and measuring every ingredient before heat touches the pan",
        },
        "facts": [
            "Resting meat after cooking lets juices redistribute instead of spilling onto the board.",
            "Salting pasta water seasons noodles from the inside as they absorb liquid.",
            "Sharp knives are safer than dull ones because they need less force and slip less.",
            "Gundruk, fermented leafy greens, showcases Nepal's tradition of preservation cooking.",
        ],
    },
    "Skincare & Grooming": {
        "terms": {
            "Routine building": "introducing one product at a time and patch testing so reactions stay traceable",
            "Ingredient guides": "knowing actives like niacinamide, vitamin C and retinoids do different jobs at different times of day",
            "Sunscreen myths": "correcting beliefs such as darker skin needing no SPF or sunscreen failing indoors near windows",
            "Skin barrier": "the lipid layer that locks moisture in; harsh over-cleansing strips and irritates it",
            "Retinoids": "vitamin-A derivatives that speed cell turnover, best introduced slowly at night",
            "Beard care": "regular washing, oil and trimming against ingrowns for healthier growth",
        },
        "facts": [
            "Broad-spectrum SPF thirty applied daily is the single most evidence-backed anti-aging step.",
            "Sunscreen needs reapplying every two hours outdoors, since filters degrade with UV exposure.",
            "Retinoids cause initial dryness, so buffering with moisturizer eases adjustment weeks.",
            "Over-exfoliating damages the barrier, causing the very breakouts it aims to cure.",
        ],
    },
    "Fashion & Style": {
        "terms": {
            "Wardrobe basics": "versatile neutral pieces that combine easily and outlast trend cycles",
            "Seasonal trends": "short-lived industry cycles worth sampling only when they fit your existing style",
            "Thrifting": "secondhand shopping that saves money, reduces textile waste and surfaces unique finds",
            "Capsule wardrobe": "a small set of interchangeable clothes covering most occasions",
            "Fit principles": "shoulder seams and trouser breaks matter more than brand labels",
            "Fabric care": "washing cold and air-drying extends garment life significantly",
        },
        "facts": [
            "Tailoring cheap clothes beats buying expensive clothes that fit poorly.",
            "Natural fibers breathe differently than synthetics, changing comfort across seasons.",
            "Most garment emissions come from washing and drying, not manufacture alone.",
            "A capsule wardrobe reduces decision fatigue as well as spending.",
        ],
    },
    "Parenting": {
        "terms": {
            "Screen time limits": "pediatric guidance favors avoiding screens under eighteen months and co-viewing small amounts thereafter",
            "Sleep training": "teaching babies to self-settle through consistent routines, whatever method parents choose",
            "Toddler tantrums": "normal emotional overwhelm handled best by calm presence and firm, kind boundaries",
            "Positive reinforcement": "specifically praising desired behavior so it repeats more reliably",
            "Bedtime routines": "predictable sequences that cue sleep and cut bedtime resistance",
            "Secure attachment": "trust built by responsive caregiving, giving children a base to explore from",
            "Sibling rivalry": "normal competition reduced by avoiding comparisons and coaching negotiation",
            "Gentle discipline": "holding boundaries with empathy instead of punishment or permissiveness",
        },
        "facts": [
            "Consistency beats intensity: any sleep-training method works when applied predictably.",
            "Naming emotions helps toddlers regulate because labeling calms the alarm response.",
            "Co-viewed educational content teaches far better than solo viewing at young ages.",
            "Praising effort rather than traits builds children who persist through difficulty.",
        ],
    },
    "Relationships & Dating": {
        "terms": {
            "Communication tips": "active listening, I-statements and choosing calm moments for hard conversations",
            "Breakup recovery": "treating heartbreak as grief, leaning on friends and limiting contact while wounds heal",
            "Red flags": "warning patterns such as control, isolation from friends and contempt for boundaries",
            "Healthy boundaries": "clearly stated personal limits that protect wellbeing without apology",
            "Active listening": "reflecting back what you heard before responding, so partners feel understood",
            "Conflict repair": "apologizing specifically and reconnecting after fights, which predicts relationship longevity",
        },
        "facts": [
            "Contempt is the strongest documented predictor of relationship breakdown among couples.",
            "No-contact periods reduce breakup rumination better than checking ex-partners' profiles.",
            "Conflicts resolved with repair attempts strengthen bonds more than conflicts avoided entirely.",
            "Stating needs directly outperforms expecting partners to guess them.",
        ],
    },
    "Productivity": {
        "terms": {
            "Time blocking": "assigning tasks to named calendar slots instead of working from open-ended lists",
            "Deep work": "long stretches of distraction-free concentration that produce the highest-value output",
            "Habit tracking": "recording streaks so visible consistency motivates repetition",
            "Study techniques": "methods like spaced repetition and practice testing that beat passive rereading",
            "Two-minute rule": "doing tasks that take under two minutes immediately rather than tracking them",
            "Priority matrix": "sorting tasks by urgency and importance to decide what deserves attention first",
        },
        "facts": [
            "Context switching costs minutes of refocus each time, so batching similar tasks pays.",
            "Practice testing produces stronger retention than rereading notes by a wide margin.",
            "Notifications fragment attention even when ignored, because suppression itself consumes focus.",
            "Planning tomorrow's top task tonight removes morning decision friction.",
        ],
    },
    "Adventure Tourism": {
        "terms": {
            "Everest Base Camp": "the Khumbu trek reaching 5,364 meters, demanding acclimatization days at Namche and Dingboche",
            "Annapurna Circuit": "the classic teahouse trek crossing the 5,416-meter Thorong La pass",
            "Mountaineering permits": "TIMS cards and park entry fees for treks; climbing peaks require NMA permits",
            "Altitude acclimatization": "ascending gradually and sleeping low so the body adapts to thinner air",
            "Teahouse trekking": "lodging in village guesthouses that keeps Himalayan treks self-supported and light",
            "Trek insurance": "coverage including helicopter evacuation, essential above treeline where rescue costs soar",
        },
        "facts": [
            "Climb high, sleep low is the acclimatization rule that minimizes altitude sickness risk.",
            "Descending is the definitive treatment for worsening altitude illness, whatever the cause.",
            "Thorong La crossing is safest started before dawn to avoid afternoon winds.",
            "Weather windows decide summit attempts more than fitness does on high peaks.",
        ],
    },
    "Cultural Tourism": {
        "terms": {
            "Lumbini pilgrimage": "visiting the Buddha's birthplace, a UNESCO site centered on the Maya Devi temple",
            "Buddhist circuits": "routes linking stupas and monasteries such as Boudhanath and Swayambhu",
            "Pashupatinath heritage": "the major Shiva temple complex on the Bagmati river, listed by UNESCO",
            "Heritage tourism": "travel whose spending supports conservation but risks degrading fragile sites if unmanaged",
            "Homestay experiences": "staying with host families, which channels income directly into communities",
            "Festival tourism": "planning trips around events like Dashain or Indra Jatra for living-culture access",
        },
        "facts": [
            "Lumbini's sacred garden marks the traditional birth spot of Siddhartha Gautama around 563 BCE.",
            "Boudhanath stupa's eyes gaze in four directions, symbolizing omniscient awareness.",
            "Overtourism wears stone steps and frescoes faster than weather alone ever could.",
            "Community homestays keep tourist revenue local rather than leaking to outside operators.",
        ],
    },
    "Budget Travel": {
        "terms": {
            "Flight deals": "flexible dates and midweek departures typically price lower than fixed holiday travel",
            "Backpacking routes": "regions like Southeast Asia and Nepal where daily costs stretch small budgets far",
            "Travel itineraries": "loose plans with buffer days that let you seize cheap opportunities en route",
            "Shoulder season": "the window either side of peak season balancing good weather with low prices",
            "Street food economics": "local eateries cost a fraction of tourist restaurants and often taste better",
            "Points and miles": "loyalty currency earned through everyday spend and redeemed for flights and stays",
        },
        "facts": [
            "Tuesday and Wednesday departures historically price lowest on many domestic routes.",
            "Accommodation dominates daily budgets, so dorms and homestays stretch trips furthest.",
            "Booking one-way legs separately can beat round-trip fares on competitive routes.",
            "Travel insurance costs little relative to the evacuation bills it prevents.",
        ],
    },
    "Sports Science": {
        "terms": {
            "Biomechanics": "analyzing forces and joint motion to improve technique and prevent injury",
            "Aerobic threshold": "the highest sustainable intensity where lactate production still balances clearance",
            "Kinematics": "describing motion itself, positions and velocities, without reference to forces",
            "VO2 max": "maximal oxygen uptake, the classic ceiling marker of aerobic fitness",
            "Periodization": "structuring training into phases so peak fitness lands on competition dates",
            "Recovery science": "sleep, nutrition and rest intervals through which adaptation actually occurs",
        },
        "facts": [
            "Most endurance gains come from large volumes of easy work below threshold.",
            "Improving technique economy raises performance without raising VO2 max at all.",
            "Tapering before competition restores freshness while retaining trained capacity.",
            "Heat adaptation expands plasma volume, improving performance in cool conditions too.",
        ],
    },
    "Football (Soccer)": {
        "terms": {
            "Tactics breakdown": "how formations and pressing schemes shape where space and chances appear",
            "Transfer news": "signing moves permitted during summer and winter registration windows",
            "Fantasy leagues": "games scoring managers on real players' weekly performances",
            "Expected goals": "xG, a chance-quality model estimating each shot's scoring likelihood from location and context",
            "Offside rule": "attackers beyond the second-last defender at the moment the ball is played are offside",
            "Counter-attacking": "deliberately conceding possession to strike quickly into transition space",
        },
        "facts": [
            "A striker positioned beyond the second-last defender when the pass leaves the passer's foot is offside.",
            "High pressing trades defensive exposure for turnovers closer to goal.",
            "Expected goals strips luck from scorelines, revealing underlying team quality.",
            "Winter transfer windows run about a month, varying slightly by league.",
        ],
    },
    "Cricket Analytics": {
        "terms": {
            "Batting technique": "alignment, balance and timing fundamentals behind consistent run scoring",
            "IPL analysis": "data-rich study of franchise T20 cricket's matchups and auction economics",
            "Fantasy cricket": "points games mirroring real player performances across formats",
            "Match strategy": "phase plans like powerplay aggression versus middle-overs rotation",
            "Strike rate": "runs scored per hundred balls, the T20 currency of batting tempo",
            "DLS method": "rain-adjusted targets recalculating chases from resources remaining, wickets and overs alike",
        },
        "facts": [
            "The DLS method converts overs and wickets left into a single resource percentage.",
            "Powerplay field restrictions make the first six overs the cheapest scoring phase in T20.",
            "Bowling yorkers wide of yorker length concedes fewer death-over runs than length balls.",
            "Pitch wear shifts optimal targets between innings in multi-day matches.",
        ],
    },
    "Gaming & Esports": {
        "terms": {
            "Speedrunning": "finishing games as fast as possible, split into categories like any-percent and glitchless",
            "Console vs PC": "choosing between standardized convenience and upgradeable performance plus mod support",
            "Indie games": "small-studio titles that frequently pioneer mechanics before big studios adopt them",
            "Esports tournaments": "professional competitions with brackets, sponsors and prize pools",
            "Metagame": "the evolving consensus of dominant strategies that patches continually reshape",
            "Frame rate": "renders per second, where higher values cut input latency and smooth motion",
        },
        "facts": [
            "Any-percent runs allow skips and glitches, unlike glitchless categories.",
            "Higher frame rates shorten the delay between clicking and seeing the result.",
            "Balance patches rotate the metagame, keeping competitive play from freezing around one strategy.",
            "Indie hits like Among Us reached massive audiences years after quiet launches.",
        ],
    },
    "Cinema Studies": {
        "terms": {
            "Cinematography": "the visual craft of camera movement, lighting and composition serving story",
            "Screenplay structure": "the three-act shape of setup, confrontation and resolution underlying most features",
            "Color grading": "post-production tone shaping that steers mood scene by scene",
            "Montage editing": "juxtaposing shots so their sequence creates meaning neither frame holds alone",
            "Mise-en-scene": "everything placed within the frame, from blocking to props to lighting",
            "Diegetic sound": "audio whose source exists inside the story world, unlike scored narration",
        },
        "facts": [
            "The Kuleshov effect showed audiences read emotion into neutral faces by adjacent shots.",
            "Three-act structure places the midpoint reversal roughly halfway through runtime.",
            "Cool grades push unease while warm grades signal intimacy, grading conventions audiences feel.",
            "Deep-focus shots let viewers choose where to look, staging several story layers simultaneously.",
        ],
    },
    "Music Theory & Production": {
        "terms": {
            "Harmonic progression": "chord sequences like I-V-vi-IV that anchor most popular songs",
            "Beat making": "programming drums and grooves that give tracks their rhythmic identity",
            "DAW tutorials": "training in digital audio workstations covering recording, MIDI and mixing",
            "Key signatures": "sharps and flats defining which notes belong to a piece's scale",
            "Tempo and BPM": "beats per minute setting a track's pace and energy",
            "Sidechain compression": "ducking one track whenever another plays, tightening mixes automatically",
        },
        "facts": [
            "The I-V-vi-IV loop appears in hundreds of pop hits across decades.",
            "Sidechaining bass to kick creates the pumping motion central to dance music.",
            "Major and minor keys share signatures; mode depends on which note feels like home.",
            "Reference tracks during mixing reveal frequency imbalances faster than solo listening.",
        ],
    },
    "Photography": {
        "terms": {
            "Camera settings": "balancing aperture, shutter speed and ISO to expose light correctly",
            "Composition rules": "guides like thirds and leading lines that direct the viewer's eye",
            "Editing basics": "cropping, exposure and color adjustments that finish an image without faking it",
            "Golden hour": "the soft warm light shortly after sunrise and before sunset flattering most subjects",
            "Depth of field": "how much of a scene stays sharp, widened by smaller apertures",
            "RAW format": "unprocessed sensor data preserving latitude for exposure correction later",
        },
        "facts": [
            "Wide apertures like f/1.8 blur backgrounds, isolating subjects sharply.",
            "Slower shutter speeds blur motion, so handheld shots rarely survive below one over focal length.",
            "Golden-hour shadows stretch long, adding depth flat midday light lacks.",
            "RAW files recover blown highlights far better than JPEGs can.",
        ],
    },
    "Architecture": {
        "terms": {
            "Floor planning": "arranging rooms for function, circulation and daylight access",
            "Building materials": "structural choices like concrete, steel and timber with distinct spans and footprints",
            "Sustainable design": "passive solar orientation, insulation and efficient systems cutting lifetime energy use",
            "Site orientation": "placing buildings according to sun path, wind and views",
            "Load-bearing structure": "walls and columns carrying roof loads, distinct from non-structural partitions",
            "Scale and proportion": "dimensioning spaces to human bodies and sightlines for comfort",
        },
        "facts": [
            "South-facing glazing collects winter sun in the northern hemisphere while overhangs block summer highs.",
            "Open floor plans trade acoustic privacy for flexible daylight sharing.",
            "Concrete's compressive strength pairs with steel reinforcement wherever tension arises.",
            "Ceiling height changes perceived spaciousness more than equal floor area does.",
        ],
    },
    "Architectural History": {
        "terms": {
            "Brutalism": "the raw-concrete style of the postwar decades expressing structure honestly and monumentally",
            "Gothic vaulting": "pointed arches and ribbed vaults that let cathedrals soar with walls of glass",
            "Bauhaus philosophy": "form follows function, merging art, craft and industrial design, taught from 1919",
            "Pagoda style": "tiered multi-roof temples characteristic of Newar architecture, exemplified by Bhaktapur's Nyatapola",
            "Modernism": "the twentieth-century movement rejecting ornament in favor of volume and machine production",
            "Classical orders": "Doric, Ionic and Corinthian column styles codifying Greek proportions",
        },
        "facts": [
            "Nyatapola temple's five tiers rise on successively wider plinths guarding stairways of guardian figures.",
            "Flying buttresses transferred Gothic roof thrust outward, freeing walls for stained glass.",
            "Bauhaus closed under Nazi pressure in 1933, scattering its teachers worldwide.",
            "Brutalist estates now divide preservationists, loved as heritage and loathed as eyesores.",
        ],
    },
    "Graphic Design": {
        "terms": {
            "Typography": "typeface selection, hierarchy and spacing that set tone and readability",
            "Color theory": "wheel relationships like complementary and analogous pairs guiding harmony",
            "Figma workflows": "collaborative vector-based interface design with reusable components and live cursors",
            "Logo design": "marks kept simple, memorable and scalable so they survive every size and medium",
            "White space": "deliberate emptiness that improves comprehension and directs attention",
            "Grid systems": "invisible column structures aligning elements into visual order",
        },
        "facts": [
            "Pairing one serif with one sans-serif creates contrast without clutter.",
            "Complementary colors sit opposite on the wheel and intensify each other when juxtaposed.",
            "Logos must read at sixteen pixels and on billboards alike, which forces simplicity.",
            "Increasing white space around a headline raises its perceived importance.",
        ],
    },
    "UI/UX Design": {
        "terms": {
            "Wireframing": "sketching low-fidelity layouts to settle structure before visual polish begins",
            "User research": "interviews and tests that replace assumptions about users with observed behavior",
            "Design systems": "shared libraries of components and rules keeping products consistent at scale",
            "Prototyping": "building clickable flows that validate ideas before engineering commits code",
            "Usability testing": "watching real users complete tasks to surface friction designers cannot see",
            "Affordances": "visual cues signaling what is clickable, draggable or scrollable",
        },
        "facts": [
            "Five users uncover roughly eighty-five percent of usability problems in moderated tests.",
            "Wireframes deliberately exclude color and imagery so feedback stays structural.",
            "Consistent component behavior lets users transfer learning across screens.",
            "Users scan interfaces in F-shaped reading patterns, so key actions go where eyes land.",
        ],
    },
    "Interior Design": {
        "terms": {
            "Space planning": "arranging furniture and zones so circulation flows without obstruction",
            "Lighting design": "layering ambient, task and accent light to transform how a room feels",
            "Furniture layout": "grouping seating into conversation clusters with clear walking paths",
            "Color palettes": "balanced schemes often following a sixty-thirty-ten dominant-secondary-accent split",
            "Texture layering": "mixing materials like wood, linen and metal so neutral rooms still feel rich",
            "Ergonomics at home": "dimensioning desks, chairs and counters to the bodies using them",
        },
        "facts": [
            "Walkways of roughly seventy-five centimeters keep rooms navigable without squeezing past furniture.",
            "Layered lighting beats single overhead fixtures for evening comfort.",
            "The sixty-thirty-ten rule balances dominance, support and spark in a palette.",
            "Mixing matte and glossy finishes adds depth even when hues match exactly.",
        ],
    },
}
