"""Turn a topic into stored MCQ posts.

Generated questions land in the normal content tables — a `Post` with
content_type=MCQ plus its `Mcq` payload row — so they flow through the existing
feed, ranker, and /posts endpoints with no special-casing. They are attributed to
a single system creator profile, created lazily on first run.
"""

import logging
import re
from datetime import UTC, datetime
from uuid import UUID

from fastapi import HTTPException, status
from pydantic import ValidationError
from sqlalchemy import func, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from core.config import get_settings
from src.db.models import ContentType, CreatorProfile, Mcq, Post, Topic, User

from . import llm
from .prompts import MCQ_RESPONSE_SCHEMA, SYSTEM_PROMPT, build_user_prompt
from .schemas import GeneratedMcq, McqItem, QuizGenerationResult, TopicQuizResponse

logger = logging.getLogger(__name__)

# Post.difficulty is a 0..1 float; the model answers with a coarse label.
DIFFICULTY_SCORES = {"easy": 0.25, "medium": 0.5, "hard": 0.75}
DEFAULT_DIFFICULTY = 0.5

# Cap on how many stored stems are sent back to the model as "already covered".
MAX_AVOID_QUESTIONS = 25

WORDS_PER_MINUTE = 200
ANSWER_TIME_SEC = 15


def _now() -> datetime:
    # The DateTime columns are timezone-naive; keep everything naive UTC.
    return datetime.now(UTC).replace(tzinfo=None)


def _normalize(question: str) -> str:
    """Loose key for duplicate detection across runs (casing/punctuation-insensitive)."""
    return re.sub(r"[^a-z0-9]+", " ", question.casefold()).strip()


def _read_seconds(question: str, options: list[str]) -> int:
    words = len(question.split()) + sum(len(o.split()) for o in options)
    return max(20, round(words / WORDS_PER_MINUTE * 60) + ANSWER_TIME_SEC)


async def ensure_quiz_creator(db: AsyncSession) -> CreatorProfile:
    """Get (or create) the system creator profile that owns generated content."""
    settings = get_settings()
    email = settings.QUIZ_BOT_EMAIL

    profile = (
        await db.execute(
            select(CreatorProfile)
            .join(User, User.id == CreatorProfile.user_id)
            .where(User.email == email)
        )
    ).scalar_one_or_none()
    if profile is not None:
        return profile

    user = (
        await db.execute(select(User).where(User.email == email))
    ).scalar_one_or_none()

    if user is None:
        user = User(
            email=email,
            username=settings.QUIZ_BOT_USERNAME,
            password_hash=None,          # system account: no password login
            is_active=True,
            onboarding_completed=True,
        )
        db.add(user)
        try:
            await db.flush()
        except IntegrityError:
            # Another generation task created the account concurrently.
            await db.rollback()
            user = (
                await db.execute(select(User).where(User.email == email))
            ).scalar_one()

    profile = (
        await db.execute(
            select(CreatorProfile).where(CreatorProfile.user_id == user.id)
        )
    ).scalar_one_or_none()

    if profile is None:
        profile = CreatorProfile(
            user_id=user.id,
            headline="Auto-generated practice questions",
            credentials="Generated by Knova's question author model",
            authority_score=0.5,
        )
        db.add(profile)
        try:
            await db.flush()
        except IntegrityError:
            await db.rollback()
            profile = (
                await db.execute(
                    select(CreatorProfile).where(CreatorProfile.user_id == user.id)
                )
            ).scalar_one()

    return profile


async def _existing_questions(db: AsyncSession, topic_id: UUID) -> list[str]:
    return list(
        (
            await db.execute(
                select(Mcq.question)
                .join(Post, Post.id == Mcq.post_id)
                .where(Post.topic_id == topic_id)
                .order_by(Post.created_at.desc())
            )
        ).scalars().all()
    )


def _parse_items(payload) -> list[GeneratedMcq]:
    """Validate the LLM payload item-by-item, dropping anything malformed."""
    if isinstance(payload, dict):
        raw = payload.get("questions") or payload.get("mcqs") or payload.get("items")
    else:
        raw = payload

    if not isinstance(raw, list):
        logger.warning("LLM payload had no question list (keys=%s)", payload)
        return []

    items: list[GeneratedMcq] = []
    for entry in raw:
        if not isinstance(entry, dict):
            continue
        try:
            items.append(GeneratedMcq.model_validate(entry))
        except ValidationError as exc:
            logger.warning(
                "dropping invalid generated question: %s",
                "; ".join(e["msg"] for e in exc.errors()),
            )
    return items


async def generate_and_store_quiz(
    db: AsyncSession,
    topic_id: UUID,
    *,
    count: int | None = None,
    force: bool = False,
) -> QuizGenerationResult:
    """Generate MCQs for one topic and persist them as MCQ posts.

    Idempotent by default: a topic that already holds `count` questions is skipped
    unless `force=True`, and stems matching stored ones are discarded. Raises
    HTTPException(404) for an unknown topic and llm.LLMError when no provider
    could produce usable questions.
    """
    settings = get_settings()
    target = count or settings.QUIZ_MCQ_PER_TOPIC
    target = max(1, min(target, settings.QUIZ_MCQ_MAX_PER_REQUEST))

    topic = (
        await db.execute(select(Topic).where(Topic.id == topic_id))
    ).scalar_one_or_none()
    if topic is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Topic not found"
        )

    existing = await _existing_questions(db, topic.id)
    if not force and len(existing) >= target:
        return QuizGenerationResult(
            topic_id=topic.id,
            topic_name=topic.name,
            requested=0,
            skipped=True,
            reason=f"topic already has {len(existing)} MCQ(s)",
        )

    wanted = target if force else target - len(existing)

    parent_name = None
    if topic.parent_id is not None:
        parent_name = (
            await db.execute(select(Topic.name).where(Topic.id == topic.parent_id))
        ).scalar_one_or_none()

    result = await llm.generate_json(
        SYSTEM_PROMPT,
        build_user_prompt(
            topic.name,
            wanted,
            parent_topic=parent_name,
            existing_questions=existing[:MAX_AVOID_QUESTIONS],
        ),
        response_schema=MCQ_RESPONSE_SCHEMA,
    )

    items = _parse_items(result.data)
    if not items:
        raise llm.LLMError(
            f"{result.provider} returned no usable questions for '{topic.name}'"
        )

    creator = await ensure_quiz_creator(db)
    seen = {_normalize(q) for q in existing}
    now = _now()
    created = 0

    for item in items:
        if created >= wanted:
            break
        key = _normalize(item.question)
        if key in seen:
            logger.info("skipping duplicate generated question for '%s'", topic.name)
            continue
        seen.add(key)

        body = item.question
        post = Post(
            creator_id=creator.id,
            content_type=ContentType.MCQ,
            title=topic.name,
            body=body,
            word_count=len(body.split()),
            est_read_seconds=_read_seconds(item.question, item.options),
            difficulty=DIFFICULTY_SCORES.get(item.difficulty, DEFAULT_DIFFICULTY),
            topic_id=topic.id,
            status="published",
            published_at=now,
        )
        post.mcq = Mcq(
            question=item.question,
            options=item.options,
            correct_index=item.correct_index,
            explanation=item.explanation,
        )
        db.add(post)
        created += 1

    await db.commit()

    logger.info(
        "generated %d/%d MCQ(s) for topic '%s' via %s (%s)",
        created, wanted, topic.name, result.provider, result.model,
    )

    return QuizGenerationResult(
        topic_id=topic.id,
        topic_name=topic.name,
        created=created,
        requested=wanted,
        provider=result.provider,
        model=result.model,
    )


async def get_topic_quiz(
    db: AsyncSession, topic_id: UUID, *, limit: int = 50
) -> TopicQuizResponse:
    """Every MCQ stored for a topic — used to check what generation produced."""
    topic = (
        await db.execute(select(Topic).where(Topic.id == topic_id))
    ).scalar_one_or_none()
    if topic is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Topic not found"
        )

    total = (
        await db.execute(
            select(func.count(Mcq.id))
            .join(Post, Post.id == Mcq.post_id)
            .where(Post.topic_id == topic_id)
        )
    ).scalar() or 0

    rows = (
        await db.execute(
            select(Mcq, Post)
            .join(Post, Post.id == Mcq.post_id)
            .where(Post.topic_id == topic_id)
            .order_by(Post.created_at.desc())
            .limit(limit)
        )
    ).all()

    return TopicQuizResponse(
        topic_id=topic.id,
        topic_name=topic.name,
        total=total,
        items=[
            McqItem(
                post_id=post.id,
                question=mcq.question,
                options=mcq.options,
                correct_index=mcq.correct_index,
                explanation=mcq.explanation,
                difficulty=post.difficulty,
                created_at=post.created_at,
            )
            for mcq, post in rows
        ],
    )
