"""Add MCQ, FlashCard, ContentType, Tag, Interaction tables

Revision ID: 1d77cb04e1a6
Revises: bf6c3f5b6353
Create Date: 2026-07-08 17:15:51.307323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d77cb04e1a6'
down_revision: Union[str, Sequence[str], None] = 'bf6c3f5b6353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('primary_topic_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_index(op.f('ix_tags_primary_topic_id'), 'tags', ['primary_topic_id'], unique=False)
    op.create_table('flashcards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('flip_threshold_sec', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_post_id'), 'flashcards', ['post_id'], unique=True)
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('surface', sa.Enum('FEED', 'PROFILE', 'SEARCH', 'TOPIC', 'SAVED', name='interactionsurface'), nullable=False),
    sa.Column('feed_position', sa.Integer(), nullable=True),
    sa.Column('dwell_time_sec', sa.Float(), nullable=False),
    sa.Column('scroll_depth', sa.Float(), nullable=True),
    sa.Column('completion_ratio', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('engagement_weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interactions_post_created', 'interactions', ['post_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_interactions_post_id'), 'interactions', ['post_id'], unique=False)
    op.create_index(op.f('ix_interactions_surface'), 'interactions', ['surface'], unique=False)
    op.create_index('ix_interactions_user_created', 'interactions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_interactions_user_id'), 'interactions', ['user_id'], unique=False)
    op.create_table('mcqs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_index', sa.SmallInteger(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcqs_post_id'), 'mcqs', ['post_id'], unique=True)
    op.create_table('post_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'tag_id', name='uq_post_tag')
    )
    op.create_index(op.f('ix_post_tags_post_id'), 'post_tags', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_tags_tag_id'), 'post_tags', ['tag_id'], unique=False)
    # add_column does not auto-create the enum type, so create it explicitly first
    contenttype = postgresql.ENUM('TEXT', 'MCQ', 'FLASHCARD', name='contenttype')
    contenttype.create(op.get_bind(), checkfirst=True)
    op.add_column('posts', sa.Column('content_type', sa.Enum('TEXT', 'MCQ', 'FLASHCARD', name='contenttype', create_type=False), nullable=False, server_default='TEXT'))
    op.create_index(op.f('ix_posts_content_type'), 'posts', ['content_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_content_type'), table_name='posts')
    op.drop_column('posts', 'content_type')
    op.drop_index(op.f('ix_post_tags_tag_id'), table_name='post_tags')
    op.drop_index(op.f('ix_post_tags_post_id'), table_name='post_tags')
    op.drop_table('post_tags')
    op.drop_index(op.f('ix_mcqs_post_id'), table_name='mcqs')
    op.drop_table('mcqs')
    op.drop_index(op.f('ix_interactions_user_id'), table_name='interactions')
    op.drop_index('ix_interactions_user_created', table_name='interactions')
    op.drop_index(op.f('ix_interactions_surface'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_post_id'), table_name='interactions')
    op.drop_index('ix_interactions_post_created', table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_flashcards_post_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_tags_primary_topic_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
    # drop enum types left behind by the dropped column/table
    sa.Enum(name='contenttype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='interactionsurface').drop(op.get_bind(), checkfirst=True)
