"""Add curiosity_score to users

Revision ID: add_curiosity_score_to_users
Revises: add_ext_id_to_users
Create Date: 2026-07-14 13:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_curiosity_score_to_users'
down_revision: Union[str, Sequence[str], None] = 'add_ext_id_to_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('curiosity_score', sa.Float(), server_default=sa.text('0.5'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'curiosity_score')
    # ### end Alembic commands ###
